# Generated by Django 4.1.7 on 2023-02-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cartas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franquicia', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('expansion', models.CharField(max_length=20)),
                ('creador', models.CharField(max_length=10)),
                ('brillante', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='miniaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franquicia', models.CharField(max_length=20)),
                ('clase', models.CharField(max_length=20)),
                ('creador', models.CharField(max_length=10)),
                ('pintado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=10)),
                ('vista', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VideoJuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
                ('consola', models.CharField(max_length=10)),
                ('completadoAl100', models.BooleanField(default=False)),
            ],
        ),
    ]
